#!/bin/bash

RUN_DIR=/var/vcap/sys/run/cpi
PIDFILE=$RUN_DIR/cpi.pid

case $1 in

  start)
    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR

    cat > /etc/sudoers.d/cpi <<EOF
vcap ALL= NOPASSWD: /var/vcap/packages/cpi/docker-cpi

Defaults:vcap !requiretty
EOF
    chmod 440 /etc/sudoers.d/cpi

    echo $$ > $PIDFILE

    # Create a dummy process so monit will start it on system reboot
    tail -f /dev/null

    ;;

  stop)
    rm -f /etc/sudoers.d/cpi

    rm -f $PIDFILE

    ;;

  *)

  echo "Usage: ctl {start|stop}" ;;
esac